version: "3"

services:
  frontend:
    ports:
      - 3000:3000
    image: sthajay/frontend:1.0
    container_name: frontend_container
    depends_on:
      - mongodb
      - users
      - products
      - carts
  users:
    ports:
      - "4001:4001"
    image: sthajay/users:2.0
    container_name: users_container
    depends_on:
      - mongodb
  carts:
    image: sthajay/carts:2.0
    container_name: carts_container
    ports:
      - "4003:4003"
    depends_on:
      - mongodb
  products:
    ports:
      - "4002:4002"
    image: sthajay/products:2.0
    container_name: products_container
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
