version: '3'
services:
  users:
    build: ./users
    ports:
      - "4001:4001"
    depends_on:
      - db-users
  db-users:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./user/db:/data/db

  products:
    build: ./products
    ports:
      - "4002:4002"
    depends_on:
      - db-products
  db-products:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - ./product/db:/data/db

  carts:
    build: ./carts
    ports:
      - "4003:4003"
    depends_on:
      - db-carts
  db-carts:
    image: mongo
    ports:
      - "27019:27017"
    volumes:
      - ./cart/db:/data/db
