version: "3"

services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    image: sthajay/frontend:1.0
    container_name: frontend_container
  users:
    # build:
    #   context: ./users
    #   dockerfile: Dockerfile
    ports:
      - "4001:4001"
    image: sthajay/users:latest
    container_name: users_container
    depends_on:
      - mongodb
  carts:
    # build:
    #   context: ./carts
    #   dockerfile: Dockerfile
    image: sthajay/carts:latest
    container_name: carts_container
    ports:
      - "4003:4003"
    depends_on:
      - mongodb
  products:
    # build:
    #   context: ./products
    #   dockerfile: Dockerfile
    ports:
      - "4002:4002"
    image: sthajay/products:latest
    container_name: products_container
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
